### ISSUE TITLE
visualize another dataset

### ISSUE THREAD

**Issue by mab85** [photomedia/DDV#1]
@photomedia  Can i use DDV to visualize another dataset like H3K9ac or Splice and save images to disk?

**Comment by photomedia** [comment]
@mab85 sorry for the delay in responding, I was travelling.  Yes, of course, you can use DDV to visualize another dataset - that would be the point.  If you are on a Windows OS, you can use DDV 1.0 GUI (documentation: http://www.photographymedia.com/DDV/download/index.html) to enter the Accession Number of the sequence you want to visualize (or select a local FASTA file) and this will generate a master PNG file, and the deep zoom image stack files as well.  If you post the accession number or link to the  FASTA file you want to visualize, I may be willing to run the visualization for you and post the result online.  

If you need to visualize a more complex dataset such as a multi-part FASTA file, you can use the latest version of DDV (2.0) : https://github.com/josiahseaman/FluentDNA
This one is multi-platform and runs on Windows, MacOS or Linux, but it doesn't have a GUI yet, so you would need to run a command line to generate the visualizations (see the [readme ](https://github.com/josiahseaman/FluentDNA/blob/python-master/README.md) for how to do that).

**Comment by mab85** [comment]
@photomedia  Thanks for your helping, i use DDV 2.0: Windows Pre-Release. After run it  one image contain all DNA sequence appeared. I want images by number not by name, also every image as aspirate file.

**Comment by photomedia** [comment]
@mab85 I'm happy that you were able to run DDV to generate an image of the DNA sequence.  I assume that was a typo and you meant to write "separate file" rather than "aspirate".  I don't know what you mean by images by number not name.  Do you mean that you want a series of separate images indexed by the nucleotide number range?  For example, something like this?
1-5000.png
5000-10000.png
10000-15000.png
etc...
?

**Comment by mab85** [comment]
@photomedia I want image per sequence, for example if my dataset have 1000 sequence then the DDV will generate 1000 image. (just image without name of sequence above it)

**Comment by photomedia** [comment]
@mab85 I understand what you mean.  You are talking about multi-part FASTA files, right?  There is the following option:

-nt, --no_titles      No gaps for a title. Useful when combined with separate_translocations

I think that would remove the labels in the images. However, I think the separate image per sequence part in a multi-part file would require the development of a new option. I copy @josiahseaman as he may be able to comment further.

**Comment by mab85** [comment]
@photomedia Thanks for your great help, I will wait for the new option.

**Comment by josiahseaman** [comment]
Hello,
I think this is doable with the current version through the command line.
From the command prompt (or terminal) if you just use a command like
./Fluentdna.exe /path/to/sequence.fasta and no other options it will simply
place a png image with the same name as the FASTA in the same folder. So
just name the FASTA file whatever you want and there will be a pair of
files like 271.fa and 271.png.

To split one file into multiple files use existing operating system tools.
Linux terminal is really good at this, or a couple lines of python will
accomplish the task.

https://www.google.co.uk/search?q=split+one+FASTA+file&oq=split+one+FASTA+file

>

**Comment by josiahseaman** [comment]
Sorry I don't didn't notice this earlier. Issues should be opened at
https://github.com/josiahseaman/FluentDNA/issues

Here's some untested python for splitting files like you describe.

sequenceCount =1
with open(filePath, 'r') as FASTA:
    blocks = FASTA.read().split('>')
    for block in blocks:
        oname = str(sequenceCount).zfill(4) + '.fa'
        sequenceCount += 1
        with open(oname, 'w') as ofile:
            ofile.write('>' + block)

**Comment by photomedia** [comment]
@mab85 , you didn't confirm that you are asking about a multi-part FASTA file, but if you are, then as @josiahseaman suggests, you could split the file as a pre-processing step, naming then according to whatever number you want to use, and then just iterate over your files, call DDV/FluentDNA with no options for each one to generate the images.  I am closing the issue, but thanks for your question!
